apiVersion: v1
appVersion: 0.7.3
deprecated: true
description: Anchore container analysis and policy evaluation engine service
engine: gotpl
home: https://anchore.com
icon: https://anchore.com/wp-content/uploads/2016/08/anchore.png
keywords:
- analysis
- docker
- anchore
- anchore-engine
- image
- security
- vulnerability
- scanner
name: anchore-engine
sources:
- https://github.com/anchore/anchore-engine
version: 1.7.0
