pipeline {
	agent any
    stages {
        stage('Build on k8 ') {
            steps {           
                        sh 'pwd'
		        sh 'echo `pwd`'
		        sh 'cd petclinic-master'
		        sh 'echo `pwd`'
		        sh 'ls -ltr'
		        sh 'echo `pwd`'
                        sh 'cp -R petclinic-master/helm/* .'
		        sh 'ls -ltr'
                        sh 'pwd'
		        sh ' echo "Doing test deployment" '
		        sh 'helm install -n default -name petclinic-app petclinic --set image.repository=registry.hub.docker.com/vincebailey/petclinic2 --set image.tag=10 --dry-run --debug'
		        sh ' echo "Checking the namespaces" '
		        sh ' /usr/bin/kubectl get namespace '
		        sh ' echo " Creating namespace "AME"'
		        sh ' kubectl create namespace ame '
		        sh ' kubectl get namespace --show-labels'
		        sh ' echo "Doing deployment" '
		        /* sh 'helm install -n default -name petclinic-app petclinic --set image.repository=registry.hub.docker.com/vincebailey/petclinic2 --set image.tag=10' */
                        /* sh '/usr/local/bin/helm upgrade --install petclinic-app petclinic  --set image.repository=registry.hub.docker.com/docker pull vincebailey/petclinic2--set image.tag=10' */
              			
            }           
        }
    }
}
